### ISSUE TITLE
投票比率不应该用 int()

### ISSUE THREAD

**Issue by CrazyBoyFeng** [fengluo/TgCNBot#1]
https://github.com/fengluo/TgCNBot/blob/2267e7e00464d5290997e0031a16bb373d12a347/tgcnbot/vote/handlers.py#L120
投票比率用int的话，那么所有选项的比率都是0。
比如 spam 3 票、break 30 票、cancle 300 票，比率分别是 0.009:0.09:0.9，然而用 int() 转换后，就全都是 0 了。然后用 max() 找最大值，如果 spam>=3 那 max() 就永远是 spam ，否则如果 spam<3 而 break>=3 ，那么无论取消多少票，max() 永远都是 break。

**Comment by fengluo** [comment]
应该是这样的，我想了半天没想起来当初为什么这么写……
